### ISSUE TITLE
Cant Compile with Arduino IDE

### ISSUE THREAD

**Issue by bepursuant** [OpenGarage/OpenGarage-Firmware#1]
Nice project! You're about 3 months ahead of my similar project in terms of development cycle but a few years ahead in terms of C++ knowledge... I started my project late last summer but got sidetracked trying to learn Lua and get this working on a NodeMCU which sucked, but I finally decided to use the arduino environment because it's way more feature rich.

So I saw your video on this project on youtube and it was really exciting, because you've built about 90% of what I intended to make... but I cannot get the arduino example to compile, it can't find OpenGarage.h, which makes a little sense. Is that meant to be installed as a library?

Is there a way to build this in Arduino without the example wrapper?

I love the functionality you've built, and I would like to make some modifications (ex. support two open/close reed sensors instead of distance sensor) but can't get the base to compile to start working :(

**Comment by rayshobby** [comment]
OpenGarage.h is right in the OpenGarage library folder. As the instructions state clearly: you need to copy the OpenGarage folder to your Arduino's library directory.
