### ISSUE TITLE
Error Code 16 setting STA ssid/password

### ISSUE THREAD

**Issue by lawrence-jeff** [OpenGarage/OpenGarage-Firmware#10]
When I compile this and upload I couldn't get the AP mode page to update the SSID and password, whenever I submit the data it would respond with 

Error code: 16, item: ssid

Adding debug statements the ESP isn't receiving any of the arguments - I could verify they were sent in fiddler so the HTML code is correct. Digging into this it seems that the ESP webserver component being used expects the arguments to be in body of the message not query parameters when a POST - the only way I can get this to work is either adding the ?ssid=dsfdsfs&pass=sdfsdf into the body being POSTed or the easier way is to just change the page code to use a GET instead of a POST. This seems to fix it.
Not sure why this hasn't been an issue for the existing code- I am using the later arduino port 

From xhr.open('POST', comm, true); xhr.send();
to xhr.open('GET', comm, true); xhr.send();

Fixes it as well as adding the strings to the body via the send

xhr.open('POST', comm, true); xhr.send(comm);

Per this article it seems this is all to be expected as it mentions in a post the form data should be in the body
https://www.w3schools.com/tags/att_form_method.asp

**Comment by rayshobby** [comment]
Integrated your changes in the latest firmware.
