### ISSUE TITLE
1.0.6-LawrenceJeff icons not showing up

### ISSUE THREAD

**Issue by bsz0206** [OpenGarage/OpenGarage-Firmware#13]
I am using the new og_1.0.6-LawrenceJeff.bin firmware. The icons are great but they are not displayed.
can https://github.com/lawrence-jeff help?

**Comment by rayshobby** [comment]
This requires uploading the images to flash memory too. We've integrated LawrenceJeff's changes and have modified the images to be embedded in the HTML. The new firmware 1.0.7 will be released soon.
