### ISSUE TITLE
homebridge-og custom polling

### ISSUE THREAD

**Issue by identd113** [OpenGarage/OpenGarage-Firmware#15]
It seems the homebridge-og plugin polls for status every 4 minutes or so.  This would be great if it can poll more often or have a custom poll, which could be set in the config.json
This would allow automations to fire off when the garage is opened outside of the homekit system (IE RF remote)

**Comment by identd113** [comment]
Sorry, left in wrong repo!
Please Close

**Comment by Skaronator** [comment]
@identd113 You can close yourself.
