### ISSUE TITLE
Support Private Blynk Servers

### ISSUE THREAD

**Issue by ravishivt** [OpenGarage/OpenGarage-Firmware#19]
OG cannot currently be configured for a private Blynk server since it calls `Blynk.config` without overriding [Blynk's default connection options](https://github.com/blynkkk/blynk-library/blob/31c6323fd9d0998f61804c0fe5a66ab57841480c/src/Blynk/BlynkConfig.h#L20)

```
#define BLYNK_DEFAULT_DOMAIN     "blynk-cloud.com"
#define BLYNK_DEFAULT_PORT       80
```

To support private blynk servers, we'd simply need to add UI fields to override these defaults and then use them in the `Blynk.config` call.

See https://opengarage.io/forums/topic/og-with-private-blynk-server/ for more info.

**Comment by rayshobby** [comment]
Saw the PR. Will merge it with the main branch soon. Thanks.
