### ISSUE TITLE
Feature Request: Add ability to toggle door via MQTT

### ISSUE THREAD

**Issue by xbmcnut** [OpenGarage/OpenGarage-Firmware#24]
Have one deployed so thank you and working well with Home Assistant. Would be awesome to be able to control the door with a MQTT payload.

**Comment by rayshobby** [comment]
This has already been implemented:
https://github.com/OpenGarage/OpenGarage-Firmware/blob/master/OpenGarage/main.cpp#L565
basically, if you publish a message to the MQTT server with any topic and message of 'Button', or the more recommended way is to publish to topic 'OGNAME/IN/STATE' with a message of 'close' or 'open', it will trigger the door action. OGNAME is your OpenGarage device's name (you can change it in Settings).

**Comment by xbmcnut** [comment]
Thanks, but does not seem to work. My door name is "PoakaGarage" so I'm publishing either close, open or Button to `PoakaGarage/IN/STATE` and nothing happens. Can open and close from Home Assistant OK.

**Comment by xbmcnut** [comment]
Anyone tested this and confirm it is working?
