### ISSUE TITLE
ap_update.html is missing from html

### ISSUE THREAD

**Issue by kodaman2** [OpenGarage/OpenGarage-Firmware#30]
`ap_update.html` is missing from html folder, and after running html2raw, firmware fails to compile due to missing const char `ap_home_html[] PROGMEM = R` in the htmls.h file.

Just ran into this while adding a few more options to my opengarage firmware. I just copied html from original `htmls.h` to create new `ap_update.html` and ran html2raw tool. I am guessing not a lot of people have done this since it would definitely create a compile error.

**Comment by rayshobby** [comment]
it has been checked in just now.
