### ISSUE TITLE
MQTT with username/password

### ISSUE THREAD

**Issue by irqnet** [OpenGarage/OpenGarage-Firmware#33]
I've flashed og_1.1.0.bin to a new device, and it works very well.

After I did the basic configuration I've tried to enable mqtt, where I can only insert the IP of my mqtt server.  Is there any way to  configure username/password for the mqtt broker? If I submit the settings, with only the IP inserted, the webinterface stopped working and I cannot change anything after that. The device is still responding and is connected over Wifi, but http access is gone.

**Comment by rayshobby** [comment]
I don't think the MQTT feature supports username / password at the moment. If your device lost response due to MQTT, you can reset the device (check the user manual for factory reset procedure) so you can re-configure the settings.
