### ISSUE TITLE
Auto-close not working as expected

### ISSUE THREAD

**Issue by mrblack7** [OpenGarage/OpenGarage-Firmware#34]
(Creating a new issue for this)

_Originally posted by @mrblack7 in https://github.com/OpenGarage/OpenGarage-Firmware/issues/23#issuecomment-462611179_

I have it set to auto-close after 50 mins. Most of the time, it is not closing even after 1 hour... (see 
attached latest log as an example)
The latest closed event was done manually using the RF remote.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/25524883/52611665-b8d18d80-2eda-11e9-8311-88ceeb531e18.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/25524883/52611703-db63a680-2eda-11e9-9da0-2209d7975e46.png">

On a couple of occasions, I have had it auto-close within 10 mins. One time I was backing out the car and it nearly closed the door on me!

I didn't have this issue prior to updating 1.0.9  a couple of weeks ago. I was previously on 1.0.6 I think.

Let me know if you need any more info. Happy to help!

**Comment by mrblack7** [comment]
https://github.com/OpenGarage/OpenGarage-Firmware/issues/23#issuecomment-462898374

**Comment by rayshobby** [comment]
Sorry, I can't reproduce this issue and I am not aware of this being a common problem.
