### ISSUE TITLE
Cannot open/close garage with Device Key with Special characters

### ISSUE THREAD

**Issue by vinnyfuria** [OpenGarage/OpenGarage-Firmware#37]
The device key `ByC0b1xN##a9^0w$nz3k` works on the all the options pages but gets truncated (as seen via chrome developer tools) when submitting an open/close door command from the main page resulting in an inability to open/close the garage.

Mitigated by switching to a pure alpha character device key.

Firmware version 1.11

**Comment by rayshobby** [comment]
This has been addressed in the upcoming firmware 1.1.2, which integrated gabe565's fix.
