### ISSUE TITLE
Configuration option to set time and or chose NTP server

### ISSUE THREAD

**Issue by vinnyfuria** [OpenGarage/OpenGarage-Firmware#38]
I run with the opengarage completely segregated from the internet. So that log timestamps are accurate, it would be nice to be able set the time manually or, better yet, specify an IP address for time to sync via NTP.

Firmware version 1.11

**Comment by rayshobby** [comment]
This has been addressed in the upcoming firmware 1.1.2 (still in development branch):
https://github.com/OpenGarage/OpenGarage-Firmware/tree/dev-1.1.2
