### ISSUE TITLE
short MQTT server IP

### ISSUE THREAD

**Issue by idxman01** [OpenGarage/OpenGarage-Firmware#43]
All calls checking for the MQTT IP to be >8 characters need to be changed to 6 or at least 7.  A x.x.x.x public IP is probably unlikely, though I'm using 10.x.x.x which brings it to 8.  MQTT wasn't firing until I added a space after the IP, bringing it up to 9 characters.

https://opengarage.io/forums/topic/mqtt-and-home-assistant/

**Comment by glenford** [comment]
I hit this problem yesterday and had me confused, it took a while looking at the source to see why it wasn't working.  I have worked around it by adding a leading zero. e.g. 10.0.0.02, this survives a reboot.

**Comment by glenford** [comment]
I also hit this issue today.  I have worked around it by adding a leading zeros, e.g. 10.0.0.01
This survived a reboot.

**Comment by rayshobby** [comment]
This has been addressed in the upcoming firmware 1.1.2 (still in development branch):
https://opengarage.io/forums/topic/openthings-cloud-otc-beta-test-call-for-help/
it removed the requirement of 8 chars or more.
