### ISSUE TITLE
Option Request:  Set Hostname

### ISSUE THREAD

**Issue by LightAxe** [OpenGarage/OpenGarage-Firmware#44]
I'd like to be able to set the hostname (set in the dhcp request) to something sane, so I can easily use DNS resolution to address my OG.  Right now it's ESP_(random hex) rather than "opengarage". 

This is pretty low priority.

**Comment by rayshobby** [comment]
Just to let you know that this has been address in the upcoming firmware 1.1.2 (still in development branch at the moment):
https://github.com/OpenGarage/OpenGarage-Firmware/commits/dev-1.1.2
which allows setting a custom host name.
