### ISSUE TITLE
FEATURE REQUEST: Https with Lets Encrypt?

### ISSUE THREAD

**Issue by jjanderson** [OpenGarage/OpenGarage-Firmware#45]
Would be great if there was an HTTPS option, even better if this could be tied into a lets encrypt service so that we can expose the OpenGarage web server confidently... 

Thanks again for a great piece of Kit!

**Comment by matt199x** [comment]
I'd recommend just connecting to your network with a VPN. Free options such as PiVPN can quickly be set up. No reason why this should be exposed to the outside world.

**Comment by rayshobby** [comment]
Another option is to use the OTC version of the OpenGarage firmware:
https://opengarage.io/forums/topic/openthings-cloud-otc-beta-test-call-for-help/
which is our own cloud service. With OTC firmware, the phone / app connects to the OTC server securely.
