### ISSUE TITLE
Feature Request: Add temperature and humidity to Blynk

### ISSUE THREAD

**Issue by AlBrough** [OpenGarage/OpenGarage-Firmware#47]
I have tried, and not been able to add the temperature and humidity readings from a sensor to the blynk dashboard. I have worked out that Virtual pins need to be added and mapped but I have not been able to successfully compile a working version - I seem to be missing something...

**Comment by rayshobby** [comment]
This has been addressed in the upcoming firmware 1.1.2,
https://github.com/OpenGarage/OpenGarage-Firmware/tree/dev-1.1.2
which reports temperature and humidity at virtual pins V6 and V7. These values are also added to the Blynk histogram widget. If you want to display these values directly, you can add display widgets for V6 and V7 (though these will end up requiring more Blynk points so you may have to pay a couple of dollars for it).
