### ISSUE TITLE
Not using static ip

### ISSUE THREAD

**Issue by Colgaton** [OpenGarage/OpenGarage-Firmware#50]
Running firmware 1.1.0, opengarage randomly gets the IP from the DHCP instead of using the static one set. Any idea why?

**Comment by rayshobby** [comment]
This has been resolved in firmware 1.1.1.

**Comment by Colgaton** [comment]
I don't see a release for 1.1.1, is there a timeline available? Thank you.

**Comment by rayshobby** [comment]
The code in the master branch IS version 1.1.1.
