### ISSUE TITLE
Ultrasonic sensor issues

### ISSUE THREAD

**Issue by mrstegeman** [OpenGarage/OpenGarage-Firmware#56]
I recently bought two separate units. I configured them both the same. One of them is working great, but the other seems to be doing bad things.
1. When the door is physically open, OG says that it's closed, and that the distance is ~150 cm.
2. When the door is physically closed, OG says that it's open, and that the distance is 0 cm.

Did I just get a bad unit?

**Comment by rayshobby** [comment]
I suggest that you send a support ticket at:
support.openthings.io
Github is not used to provide technical support for your orders.
