### ISSUE TITLE
FW 1.1.2 Beta - MQTT non default port bug

### ISSUE THREAD

**Issue by SamForma** [OpenGarage/OpenGarage-Firmware#63]
Running Firmware 1.1.2

When trying to connect to a mosquitto broker listening on a port other than 1883, the connection is not made. I see nothing logged in the mosquitto log nor are any messages received by subscribers. 

to rule out firewall related issues, I issued a message to a new topic using mosquitto_pub while the mosquitto service is running on 1884, and was received fine by mosquitto_sub. Connections are logged properly.

**Comment by MinimalPTH** [comment]
Thank you for posting this report - I just spent several hours trying to understand why I was not able to publish to my MQTT server on a non-standard port.  Here's hoping for a quick resolution.

**Comment by jduff001** [comment]
Please clarify if port 1883 works.. but a custom port is not working?

**Comment by MinimalPTH** [comment]
Port 1883 works.  Custom port does not work.

**Comment by Normanras** [comment]
Hi - I recently bought OpenGarage and just added a DHT22 to the sensor to G05 and confirmed that it is working via the web GUI. But I am not getting any information via MQTT. Either via Home Assistant or the MQTTool app. I can confirm that my other MQTT events are firing and being picked up, but OpenGarage is not transmitting anything. Server, port, user and pass are all correct and working with other devices.

**Comment by rayshobby** [comment]
This issue should be fixed in the now released firmware 1.2.0. Previously 1.1.2 beta was using fixed port 1883. This has now been fixed.

**Comment by sumoneelse** [comment]
Thank you!  Unfortunately I cannot use 1.2.0 as I'm on an older hardware version. I'm glad others will benefit from this fix though.
