### ISSUE TITLE
Possible to make use of breakbeam sensor?

### ISSUE THREAD

**Issue by johntdyer** [OpenGarage/OpenGarage-Firmware#65]
Hello,
  
   I would liek to know if I can get the status of my break beam sensor in open-garage so I can know when my door is blocked .  Thanks

-John

**Comment by rayshobby** [comment]
This is not easy to implement unfortunately. Depending on what's your garage system's brand name and model number, the beam sensors don't always work at the same voltage. Some are at high voltage (24V), some are at low voltage. It's better to check your garage system on a case by case basis. It's difficult to design a universal solution for all systems.
