### ISSUE TITLE
Support for two clicks to open/close?

### ISSUE THREAD

**Issue by thomrburg** [OpenGarage/OpenGarage-Firmware#66]
I have an older garage opener that requires two clicks within three seconds to open or close. Is there a way to support this?

**Comment by rayshobby** [comment]
You can certainly modify the firmware to support this. I think this is a rather rare type of garage opener and unfortunately we don't have plan to add this as a standard feature. I've personally never seen other openers like this (I've seen openers where a double click triggers the light, but not the garage door action).
