### ISSUE TITLE
Error at power on (relay click )

### ISSUE THREAD

**Issue by mattthhdp** [OpenGarage/OpenGarage-Firmware#67]
Everything is working as it should but each time i turn off (power outage) and power on the device, the relay click 2 short time (+/- 500ms) and 1 long time (+/-  2000ms)
I also have reflashed with nocemcu pyflasher (yes, wypes all data)
and note that if i reboot(via web interface)  or press the reset on the d1mini the relay dosent click.

the relay is on pin D8 of a wemo d1 mini. any idea ?

**Comment by rayshobby** [comment]
I am not aware of this issue and have not heard of other report of this issue. Is it possible that you are using a relay module that's active low?
