### ISSUE TITLE
OpenGarage Firmware 1.1.2 API Document - wrong RSSI unit?

### ISSUE THREAD

**Issue by dreimer1986** [OpenGarage/OpenGarage-Firmware#68]
In following issue I was explained that your API Documenttion says the RSSI signal strength unit is dB and not dBm. I think that's a typo as the OpenGarage Web-UI uses dBm, too. It makes more sense IMO either.

Issue I opened for Home Assistant: https://github.com/home-assistant/core/issues/58930

Document I am talking about: https://github.com/OpenGarage/OpenGarage-Firmware/blob/master/docs/OGAPI1.1.2.pdf

**Comment by rayshobby** [comment]
You are right, this should be in unit of dBm -- the homepage does display this in dBm. It's a typo in the API document. Will fix it right away. Thanks for pointing this out.
