### ISSUE TITLE
MQTT - No data being sent (Build 1.1.2)

### ISSUE THREAD

**Issue by Normanras** [OpenGarage/OpenGarage-Firmware#69]
Hi - I recently bought OpenGarage and just added a DHT22 to the sensor to G05 and confirmed that it is working via the web GUI. But I am not getting any information via MQTT. Either via HomeAssistant or the MQTTool app (iOS). 

I can confirm that my other MQTT events are firing and being picked up, but OpenGarage is not transmitting anything. Server, port (1883), user, and pass are all correct and working with other devices. I've tried both the default topic and changing the topic to something new. Maybe I'm missing something?

EDIT: The HA integration populated the rest of the entities, but I'm still not getting anything over MQTT. FYI. Not a huge deal now, but it is strange.

**Comment by rayshobby** [comment]
We tested the firmware with mosquitto in Linux and it's correctly sending MQTT messages. I am not sure about the HA integration. You may have to post this as a question to whoever wrote the HA integration.
