### ISSUE TITLE
click_relay to use set_relay?

### ISSUE THREAD

**Issue by eharris** [OpenGarage/OpenGarage-Firmware#7]
Seems like the code would be a bit cleaner if ```click_relay()``` were to use ```set_relay()``` to avoid another place to change the pin definition if it needed to be.

**Comment by rayshobby** [comment]
This has been addressed in the upcoming firmware 1.0.6:
https://github.com/OpenGarage/OpenGarage-Firmware/blob/master/OpenGarage/OpenGarage.h#L64
