### ISSUE TITLE
64 Byte MQTT usernames needed

### ISSUE THREAD

**Issue by sumoneelse** [OpenGarage/OpenGarage-Firmware#70]
I am using an MQTT broker called flespi. Authentication is handled using a 64 byte user name.  Example:

2bypoemSP5tE9gf0O4jRu7nMQZMlVsSNtg3FjdnY8Fq6JvWnn35H0ghG4TPPbxrs

More info:  https://flespi.com/kb/tokens-access-keys-to-flespi-platform

I am unable to use this username as it is longer than the field in the OpenGarage UI will allow me to paste.  

Can the username field accommodate a username long enough to handle these strings?

**Comment by rayshobby** [comment]
well, that's a bizarrely long user name, but sure, this will be addressed in firmware 1.2.0. It's just a matter of changing the maxlength of mqtt user name to 64. You can actually make the change yourself and compile the firmware.
