### ISSUE TITLE
Firmware 1.2.1 reports version is 1.2.0

### ISSUE THREAD

**Issue by davidjb** [OpenGarage/OpenGarage-Firmware#79]
I recently upgraded my OpenGarage to 1.2.1 using https://github.com/OpenGarage/OpenGarage-Firmware/blob/master/Compiled/og_1.2.1.bin  but the firmware version is reported as 1.2.0 (eg `“fwv":120` via the `/jc` API and visually on the homepage).

**Comment by rayshobby** [comment]
Yes I am aware of it. It will be fixed in the next firmware version change. The only difference between 1.2.0 and 1.2.1 is that 1.2.1 uses the updated OTF library, which fixed a bug that isn't relevant to OpenGarage actually. So it doesn't affect any functionality of OpenGarage.
