### ISSUE TITLE
Be more clear on preventing or warning about updating to 1.2.1

### ISSUE THREAD

**Issue by onedr0p** [OpenGarage/OpenGarage-Firmware#80]
I just tried to update to 1.2.1 and read a bit of the release notes, but I didn't catch the bit about the breaking change for older devices.

I feel like this should have been bolded on the device firmware update page on the device web UI itself with a note to save your settings incase they get reset. The open-garage firmware update to 1.2.1 did not take and now I have to try and flash it manually back to the older version.

I hope I did not brick it!

**Comment by rayshobby** [comment]
Will do.
