### ISSUE TITLE
Add MQTT

### ISSUE THREAD

**Issue by DynamoBen** [OpenGarage/OpenGarage-Firmware#9]
Incorporate MQTT into master.

See here: https://opengarage.io/forums/topic/mqtt-and-og/

**Comment by rayshobby** [comment]
MQTT will be supported in the upcoming firmware 1.0.7 (merging Jeff Lawrence's contributions).

**Comment by xbmcnut** [comment]
Running og_1.0.8.bin with MQTT connected and device configured as a cover in home assistant. I want to be able to open and close the garage door via MQTT which is throitically supported? Can anyone advise the publish topic and payload? I tried subscribing to GarageDoor/# and get nothing.

**Comment by DynamoBen** [comment]
MQTT control isn't implemented, only status updates. It could be added, you might want to create a new feature request ticket for that.

**Comment by xbmcnut** [comment]
Will do, thanks.
