### ISSUE TITLE
[Feature Request] MQTT interval

### ISSUE THREAD

**Issue by BillyCroan** [OpenGarage/OpenGarage-Firmware#92]
My OpenGarage reports its position about every 18 seconds.  Could we get a field to adjust the interval, with 0 meaning no repeats, only report when it changes?

[root@GW-Primary ~]# mosquitto_sub -h localhost -t 'OpenGarage' | while read MSG ; do TStamp="$( date '+%Y%m%d-%H%M%S' )" ; if [[ "${LastMSG}" != "" ]] && [[ "${LastMSG}" != "${MSG}" ]] ; then echo "${TStamp} CHANGED STATE from ${LastMSG} to ${MSG}" ; else echo "${TStamp} is ${MSG}"; fi ; LastMSG="${MSG}" ; done | tee -a /var/log/GarageDoor.log
20231030-225023 is Closed
20231030-225039 is Closed
20231030-225055 is Closed
20231030-225111 is Closed
20231030-225127 is Closed
20231030-225143 is Closed
20231030-225159 is Closed
20231030-225215 is Closed
20231030-225231 is Closed

**Comment by rayshobby** [comment]
These are in the /OUT/STATE topic. You don't need to subscribe to it. If you don't want to receive them, just unsubscribe this topic. The notifications are in the /OUT/NOTIFY topic.
