### ISSUE TITLE
OpenGarage/HA gets confused by partial door open and then close

### ISSUE THREAD

**Issue by TopBanana123** [OpenGarage/OpenGarage-Firmware#94]
I'm wondering if anyone has run into this, I am not sure if its an HA issue or an OpenGarage issue

If my garage door is closed, and I hit the button to open it, then press again to stop it half way, and then press again to close it, it gets stuck in an “Opening” state in HA

I do this from time to time, sometimes because I accidently hit the garage button to open but more often, to scare away Raccoons from the cat door

Right now OpenGarage shows CLOSED, which is correct

![image](https://github.com/OpenGarage/OpenGarage-Firmware/assets/43852644/f2cac99c-84fe-4ce0-9206-ddda9ba39cc3)

However, HomeKit shows Opening with the spinning circle

![image](https://github.com/OpenGarage/OpenGarage-Firmware/assets/43852644/15d3d273-bc1c-4e0f-8e77-2bd601735732)

And in HA, it never shows the “Closed” message, which I guess is why HomeKit is showing it in progress

![image](https://github.com/OpenGarage/OpenGarage-Firmware/assets/43852644/abcd4849-d18b-478c-8b38-9b11d1e2f061)

Is there a way to get it to poll OpenGarage every X seconds to figure out the real status?

If I reboot OpenGarage, it does not correct itself. I guess because HA hasn't queried it again

If I click on the door to "close" it (Actually it will open) it does then correct itself right away to the correct status of closed, before then changing back to opened once the door gets to the sensors

**Comment by TopBanana123** [comment]
This is what I did to fix it, if anyone has the same problem. It would be handy if this was a built in fix

![image](https://github.com/OpenGarage/OpenGarage-Firmware/assets/43852644/afea6b9e-7848-4352-b962-c1b82e72ccfb)

**Comment by rayshobby** [comment]
It sounds like this is an HA issue, as the OG firmware reports the correct state but HA doesn't. So I am closing this issue for now.
