### ISSUE TITLE
Add a second switch 

### ISSUE THREAD

**Issue by dmz006** [OpenGarage/OpenGarage-Firmware#95]
It would be great to have 2 switch sensors, to capture if door is actually fully open or closed.  

Currently with the switch && || the distance I can capture if the door is open; but not if it is totally closed.

If I put the switch on the door as it's closed and then use the distance to capture if door is open then I lose ability to track if car is in the garage if door is open.

**Comment by rayshobby** [comment]
It's pretty easy to replicate the existing code to add a second switch sensor. Just search PIN_SWITCH, it only has 3 occurrences in the firmware code. There are two spare pins that could possibly be used for it: one is GPIO5 (assuming not using a temperature sensor); the other is GPIO10 (currently not used). That said, I am hesitant to spend time implementing this feature myself. I am not sure how many users need this feature. The hardware has no exposed screw pins for a second switch sensor. Also, adding a second switch sensor will make the sensor logic more complex (i.e. there will probably be 6 or 7 different combinations). For that reason, I'd rather leave this for users to implement themselves.
