### ISSUE TITLE
Independent Switch Sensor Setting

### ISSUE THREAD

**Issue by majorsl** [OpenGarage/OpenGarage-Firmware#96]
I just replaced my older OG that suffered a near lightning strike with the newer version and I like the optional sensor switch that my older one didn't have.

I have no use for it with my garage door, however.  I was hoping it would have an independent setting since my garage has a side door.  It would be nice to monitor that door without using a battery operated sensor and I'd get extra value from OG.

**Comment by EPICmynamesBG** [comment]
@majorsl not trying to hijack the thread here, but what symptoms did your failed/failing unit show? Mine has started acting up recently, being unresponsive/timing out to web calls 90% of the time and I'm trying to determine if it has bit the dust

**Comment by majorsl** [comment]
> @majorsl not trying to hijack the thread here, but what symptoms did your failed/failing unit show? Mine has started acting up recently, being unresponsive/timing out to web calls 90% of the time and I'm trying to determine if it has bit the dust

Mine was fairly obvious. Near lightning strike on the wood line near the house.  It went off line at the same time, along with a wifi access point.  When I plug it in, the blue light flashes once briefly and that's it.  Can't reset it at all.  No beep.  There is probably a chance the flash got scrambled on it.  When I have time I might hook up my serial to USB adapter and attempt to reflash it when I see what the pinouts are for the chip.

**Comment by EPICmynamesBG** [comment]
> > @majorsl not trying to hijack the thread here, but what symptoms did your failed/failing unit show? Mine has started acting up recently, being unresponsive/timing out to web calls 90% of the time and I'm trying to determine if it has bit the dust
> 
> Mine was fairly obvious. Near lightning strike on the wood line near the house. It went off line at the same time, along with a wifi access point. When I plug it in, the blue light flashes once briefly and that's it. Can't reset it at all. No beep. There is probably a chance the flash got scrambled on it. When I have time I might hook up my serial to USB adapter and attempt to reflash it when I see what the pinouts are for the chip.

Gotcha. Mine functions a bit more than that at least, so perhaps it's not totally fried; I'll start a new thread. Thanks!

**Comment by alihaiderseohub** [comment]
typical problems people encounter with their garage doors, such as misalignment, broken springs, or malfunctioning openers. By asking this question, you're inviting members of the forum to share their experiences and solutions, which can provide valuable insights for others facing similar issues. The responses could include DIY fixes, advice  about [garage door replacement ](https://garagedoorrepairnewportnews.com/garage-door-replacement/)on when to seek professional help, and tips on preventive maintenance to avoid these problems in the first place. This not only helps you gather useful information but also contributes to the community by creating a resource for those dealing with garage door issues.

**Comment by rayshobby** [comment]
The firmware does not assume the ultrasonic distance sensor is present. If the distance sensor is not present, it will return 0. Meanwhile you can always enable the switch sensor independently, and the UI will show the sensor status. So I believe the functionality you are asking for already exists.
